travis:
  secure:
    BINSTAR_TOKEN: um8PWE9hcn3nz95E2J2F1LWhfjzq49ROeFsg9fbDlEO5c+vPp1+JLGZXkPBrht0oOm6kGbbEcfyjgdK3/ao0CTiROPjrzHnjxx+JWpd/5wfHk3eu07VEX197B4xUoPxELy2tiH02yoUqGwDxDaxs7CfuMvDkXz7EJv+INTwumBZClTfyJJHoLBDC0VYiwMFDms8rMpD2NWqkB9r7KaCKNThINab6Dcm17nRcpXM/HfeGOg2LONflx+qj43c2ABU6QpsspmT0kaYKnkEDG8gZT+B+1zT31uM4flIRHgRRZb8Mh2BXgCXb9t40KSQl3e17oaM7hQdd/0GbGOAYQoiA8OYokja6kd0bcU3yEYwbdo3+tqH4UXv1JTcUuM5UT8cjI1XIVUheSWpIh27+k5PYO65mPOf9DAIOMEKTnWR3EU07aHSE0ci7rFOP6afAkB63WI6PwoCejqYDFjaZ6E/vVsA+y29BBTmnbqghkkNL100TSLEtwbn56YsL+Yr8xykrCr6a7AGdNoQoW++XCMoVZK0acUCGJ7rs3yYGF+5s9Pef6QUxoFKPgZuwVFaY9rIdmGD66hg2tP2JzE1fjjWdMpRWxVJ0To3FnAIiR5tCxrJEtbt0kLJS1UmO/2U23TKDRgXDOHLVVIAeyVEW3n2xLZsNnk0VSd1pNR4PYcscwiI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
