travis:
  secure:
    BINSTAR_TOKEN: n/+c05+2AXaDRXHRtsbWDkvtSDAvHBjBani2tRXunfliFtqO0/U0jshVkQ5XNALRSp9BOBq46E42I07gB7eJhy4LYCjXzc5CaBNMHmVnesaKG/UW/sESNjsH+OdmBzFFEUpKm3caHah09e69lcKqEklIF8QkGNPZ+fvXb0brha43lUZCjIN6W/3CKib+521FrdD+1TrlDy6Zto8t3IDUmBQpVSPrXcy7NhhdfYa7YyNvZalIZESS7SBGkWa8dJqU98iLfhfd6EYw6+llP3sftBqsMyuNWlMm3S2UtHLStCZ4EzlSsCF2jfT4jNUWQxOBTR4PCZhc/KlHqVWbavtKwUDxXarY4qF6HEfOK3iYrPafWUaRKGVCbKz3POVsSgcSYRdSq1eBZPEUuu0A1X0XZ4JLXplMVxlwPeO90rH2+ZeAOhtWRWhk+XJa/sOIylXlEgAB3jQZIi+zoBZNxW14+buowQeXWhkVG4/KtKUnK2wcV3WqQmNkJ511ZPdRQU/VQwkv36e1eFvgcsi3fKOxLKqoOAKqcyCOIg6KgCJKA3gh/J8XrDQ//qIrSaD2Kb9K7T5pFnhBur52iGkoOGc7fvgTkGCgH272/bXBJGIfoOvP3bclpCeBhBz54bH6x+rDf1EKwgvlL9sjVB+iiEAGCf+mxFodAbFExmORtBbRrD0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
